### ISSUE TITLE
Google started shipping zsh-specific files

### ISSUE THREAD

**Issue by andreis** [littleq0903/gcloud-zsh-completion#6]
Sorry

```
➜  ~/3rd/google-cloud-sdk  ls -l *zsh*
-rw-r--r--  1 andrei  staff  462 30 Apr 18:43 completion.zsh.inc
-rw-r--r--  1 andrei  staff  278 30 Apr 18:43 path.zsh.inc
```

**Comment by littleq0903** [comment]
I noticed this, but because there's special tuning in this project, I can't use it currently.

should find out a way to make options generated automatically, and some special options are still configurable.

**Comment by littleq0903** [comment]
This is actually a converted version based on bash version of completion. so it won't be full functional in zsh case.

**Comment by andreis** [comment]
Sounds good. :) Have you tried talking to the gcloud sdk maintainers about merging your work?

**Comment by littleq0903** [comment]
Yes, i met him already, what I told you is the result of our discussion, so I tend to contribute another project they used to generate bash completion, it's based on Python.

They use argcomplete to generate bash completion script:
https://github.com/kislyuk/argcomplete

**Comment by andreis** [comment]
Ah cool. All the best then! :)
